name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  http: ^1.3.0
  flutter_native_splash: ^2.4.4
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - images/day.gif
    - images/night.gif
    - images/splash.png
    - images/icon.png
    - .env

  fonts:
    - family: Minecraft
      fonts:
        - asset: fonts/MinecraftRegular.otf

flutter_native_splash:
  color: "#1F1D1F"
  image: images/splash.png
  android_12:
    color: "#14161F"
    image: images/splash.png